package at.quickme.ksync

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import io.github.smyrgeorge.sqlx4k.QueryExecutor
import io.github.smyrgeorge.sqlx4k.processor.RepositoryProcessor.Prefix
import io.github.smyrgeorge.sqlx4k.processor.TableProcessor
import io.github.smyrgeorge.sqlx4k.processor.TypeNames
import kotlinx.serialization.Serializable

class EventRepositoryProcessor(
    private val options: Map<String, String>,
    private val logger: KSPLogger,
    private val codeGenerator: CodeGenerator,
) : SymbolProcessor {

    var processed = false

    /**
     * Processes repository symbols annotated with a specific annotation, validates these symbols,
     * and generates Kotlin code for their associated functionality. The generated code is written
     * to a new file using a specified file name and package.
     *
     * @param resolver The `Resolver` instance used to discover and resolve symbols annotated
     *                 with the specified repository annotation.
     * @return A list of `KSAnnotated` symbols that could not be processed due to validation errors.
     */
    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (processed)
            return emptyList()
        val repoSymbols = resolver
            .getSymbolsWithAnnotation(TypeNames.REPOSITORY_ANNOTATION)
            .filterIsInstance<KSClassDeclaration>()
            .toList()

        if (repoSymbols.isEmpty())
            return emptyList()

        val outputPackage = options[TableProcessor.PACKAGE_OPTION]
            ?: error("Missing ${TableProcessor.PACKAGE_OPTION} option")
        logger.info("[RepositoryProcessor] Output package: $outputPackage")

        val useContextParameters = options[ENABLE_CONTEXT_PARAMETERS_OPTION]?.toBoolean() ?: false
        logger.info("[RepositoryProcessor] Enable context parameters: $useContextParameters")


        val fileSpec = FileSpec.builder(outputPackage, OUTPUT_FILENAME)
            .addFileComment("Generated by ksync-codegen. DO NOT EDIT.")


        val repositorySource = TypeSpec.interfaceBuilder("RepositoryEventSource")
            .addModifiers(KModifier.SEALED)
            .addAnnotation(Serializable::class)
            .addSuperinterface(RepositoryEventBase::class.asClassName())
            .build()
        fileSpec.addType(repositorySource)


        val crudFunctionNames = listOf("update", "delete", "insert")
        // For each repository interface, find methods annotated with @Query
        val validatedRepos = repoSymbols.filter { it.validate() }
        validatedRepos.forEach { repo ->
            if (repo.classKind != ClassKind.INTERFACE)
                error("@Repository is only supported on interfaces (${repo.qualifiedName()}).")

            // Extract domain and mapper from @Repository annotation on the interface
            val (domainDecl) = parseRepositoryAnnotation(repo, useContextParameters)
            fileSpec.addImport(domainDecl.packageName.asString(), domainDecl.simpleName())

            // Find all methods declared in the interface
            val fnsAll = repo.getAllFunctions()
                .filter { fn ->
                    fn.annotations.any { it.qualifiedName() == TypeNames.QUERY_ANNOTATION } ||
                            crudFunctionNames.contains(fn.simpleName())
                }
                .toList()


            // Determine implementation class name
            val implName = repo.simpleName() + "Events"
            logger.info("[RepositoryProcessor] Generating implementation object $implName for ${repo.qualifiedName()}")


            val repositoryInterface = TypeSpec.interfaceBuilder(implName)
                .addModifiers(KModifier.SEALED)
                .addAnnotation(Serializable::class)
                .addSuperinterface(
                    ClassName(
                        outputPackage,
                        repositorySource.name!!
                    )
                )


            // Generate @Query-based methods according to prefixes:
            // findAll/findAllBy/findOneBy/deleteBy/countBy/execute and also *All variants
            fnsAll.forEach { fn ->
                val functionParameters = fn.mapFunctionParameters(domainDecl)
                val constructorParams = functionParameters.drop(if (useContextParameters) 0 else 1)

                val prefix = parseMethodPrefix(fn.simpleName())
                val allowedPrefixes =
                    listOf(Prefix.EXECUTE, Prefix.DELETE_BY, Prefix.DELETE_ALL, Prefix.COUNT_ALL, Prefix.COUNT_ALL_FLOW)
                if (!crudFunctionNames.contains(fn.simpleName()) && !allowedPrefixes.contains(prefix))
                    return@forEach

                val runFunction = FunSpec.builder("run")
                    .addModifiers(KModifier.OVERRIDE, KModifier.SUSPEND)
                    .returns(fn.returnType!!.toTypeName())

                if (useContextParameters) {
                    runFunction.contextParameter("context", QueryExecutor::class)
                    runFunction
                        .beginControlFlow("return with(context)")
                        .addStatement(
                            "repositoryProvider.resolve(%T::class).%L(%L)",
                            repo.toClassName(),
                            fn,
                            functionParameters.joinToString(", ") { it.name }
                        )
                        .endControlFlow()
                } else {
                    runFunction.addParameter("context", QueryExecutor::class)
                    runFunction.addStatement(
                        "return repositoryProvider.resolve(%T::class).%L(%L)",
                        repo.toClassName(),
                        fn,
                        functionParameters.joinToString(", ") { it.name }
                    )
                }

                runFunction.addParameter("repositoryProvider", RepositoryProvider::class)


                val functionClass = TypeSpec.classBuilder(fn.simpleName())
                    .addAnnotation(Serializable::class)
                    .primaryConstructor(
                        FunSpec.constructorBuilder()
                            .addParameters(constructorParams)
                            .build()
                    )
                    .addSuperinterface(ClassName(outputPackage, implName))
                    .addFunction(runFunction.build())
                    .addProperties(constructorParams.map {
                        PropertySpec.builder(it.name, it.type)
                            .initializer(it.name)
                            .build()
                    })
                    .build()
                repositoryInterface.addType(functionClass)
            }
            fileSpec.addType(repositoryInterface.build())
        }


        // Write the generated file
        try {
            fileSpec.build().writeTo(
                codeGenerator = codeGenerator,
                aggregating = true,
                originatingKSFiles = repoSymbols.map { it.containingFile!! },
            )
            logger.info("Generated: $OUTPUT_FILENAME")
        } catch (e: Exception) {
            logger.error("Error generating file: $e")
        }

        processed = true

        val unableToProcess = repoSymbols.filterNot { it.validate() }.toList()
        return unableToProcess
    }

    /**
     * Parses the `@Repository` annotation on the provided repository interface, validates its conformance to the
     * expected structure, and extracts the associated domain type and mapper information.
     *
     * This method ensures that the annotated repository interface extends the correct base interface
     * (e.g., `CrudRepository` or `ContextCrudRepository`) with a valid domain type parameter. Additionally,
     * it verifies that the domain type is annotated with `@Table` and that a mapper is explicitly declared within
     * the `@Repository` annotation.
     *
     * @param repo The repository interface represented as a `KSClassDeclaration`. This class declaration must
     *             be annotated with `@Repository` and implement the appropriate `CrudRepository` interface.
     * @param useContextParameters A flag indicating whether the `ContextCrudRepository` interface
     *                              is being used instead of the standard `CrudRepository`.
     * @return A pair containing the `KSClassDeclaration` of the domain type associated with the repository and
     *         the fully qualified name of the mapper type specified in the `@Repository` annotation.
     * @throws IllegalStateException if the repository interface does not conform to the expected structure, such as
     *         - Missing `@Repository` annotation
     *         - Not extending the appropriate `CrudRepository` interface
     *         - Incorrectly specified domain type
     *         - Domain type not annotated with `@Table`
     *         - Missing or unresolved mapper type in the `@Repository` annotation
     */
    private fun parseRepositoryAnnotation(
        repo: KSClassDeclaration,
        useContextParameters: Boolean
    ): Pair<KSClassDeclaration, String> {
        fun implementsCrudRepository(repo: KSClassDeclaration): KSClassDeclaration {
            val repoTypeName =
                if (useContextParameters) TypeNames.CONTEXT_CRUD_REPOSITORY
                else TypeNames.CRUD_REPOSITORY
            val repoSimpleName = repoTypeName.substringAfterLast(".")
            // find CrudRepository<T> or ContextCrudRepository<T>
            val st = repo.superTypes.map { it.resolve() }
                .firstOrNull { it.declaration.qualifiedName() == repoTypeName }
                ?: error("@Repository interface ${repo.qualifiedName()} must extend $repoTypeName<T>")
            val typeArg = st.arguments.firstOrNull()?.type?.resolve()
                ?: error("${repo.qualifiedName()} implements $repoSimpleName without type argument; expected $repoSimpleName<T>")
            val domainDecl = typeArg.declaration as? KSClassDeclaration
                ?: error("$repoSimpleName type argument must be a class on ${repo.qualifiedName()}")
            // ensure @Table
            val hasTable = domainDecl.annotations.any {
                val qn = it.qualifiedName()
                qn == TypeNames.TABLE_ANNOTATION
            }
            if (!hasTable) error("$repoSimpleName generic parameter must be @Table-annotated (${domainDecl.qualifiedName()})")
            return domainDecl
        }

        val repoAnn = repo.annotations.firstOrNull { it.qualifiedName() == TypeNames.REPOSITORY_ANNOTATION }
            ?: error("Missing @Repository annotation on interface ${repo.qualifiedName()}")

        // Enforce that the interface extends CrudRepository<T> and derive domain from T
        val domainDecl = implementsCrudRepository(repo)

        val mapperArg: KSValueArgument? = repoAnn.arguments.firstOrNull { it.name?.asString() == "mapper" }
        val mapperKSType = mapperArg?.value as? KSType
            ?: error("@Repository must declare a mapper, e.g. @Repository(mapper = FooRowMapper::class) on ${repo.qualifiedName()}")
        val mapperTypeName = mapperKSType.declaration.qualifiedName()
            ?: error("Unable to resolve mapper type for ${repo.qualifiedName()}")
        return domainDecl to mapperTypeName
    }

    private fun parseMethodPrefix(name: String): Prefix? = when {
        name == "findAll" -> Prefix.FIND_ALL
        name == "findAllFlow" -> Prefix.FIND_ALL_FLOW
        name == "deleteAll" -> Prefix.DELETE_ALL
        name == "countAll" -> Prefix.COUNT_ALL
        name == "countAllFlow" -> Prefix.COUNT_ALL_FLOW
        name.startsWith("findAllBy") && name.endsWith("Flow") -> Prefix.FIND_ALL_BY_FLOW
        name.startsWith("findAllBy") -> Prefix.FIND_ALL_BY
        name.startsWith("findOneBy") && name.endsWith("Flow") -> Prefix.FIND_ONE_BY_FLOW
        name.startsWith("findOneBy") -> Prefix.FIND_ONE_BY
        name.startsWith("deleteBy") -> Prefix.DELETE_BY
        name.startsWith("countBy") && name.endsWith("Flow") -> Prefix.COUNT_BY_FLOW
        name.startsWith("countBy") -> Prefix.COUNT_BY
        name.startsWith("execute") -> Prefix.EXECUTE
        else -> null
    }

    private fun KSDeclaration.qualifiedName(): String? = qualifiedName?.asString()
    private fun KSClassDeclaration.simpleName(): String = simpleName.asString()
    private fun KSFunctionDeclaration.simpleName(): String = simpleName.asString()
    private fun KSClassDeclaration.qualifiedName(): String? = qualifiedName?.asString()
    private fun KSAnnotation.qualifiedName(): String? = annotationType.resolve().declaration.qualifiedName?.asString()

    /**
     * Maps parameters from a KSP KSFunctionDeclaration to a list of KotlinPoet ParameterSpecs.
     *
     * @param fn The KSP function declaration whose parameters you want to map.
     * @return A list of ParameterSpec objects for use in KotlinPoet.
     */
    fun KSFunctionDeclaration.mapFunctionParameters(domainDecl: KSClassDeclaration): List<ParameterSpec> {
        return parameters.map { ksParameter ->
            // 1. Get the parameter name.
            // Using '!!' like in your original example can be risky if a parameter somehow has no name.
            val name = ksParameter.name?.getShortName()
                ?: throw IllegalStateException("Parameter in ${simpleName.asString()} lacks a name.")

            // 2. Get the parameter type.
            // This is the key fix:
            // - 'ksParameter.type' is a KSTypeReference.
            // - You must call 'resolve()' to get the KSType.
            // - Then, 'toTypeName()' (from kotlinpoet-ksp) converts the KSType to a KotlinPoet TypeName.
            val typeName = ksParameter.type.resolve()

            val type =
                if (typeName.declaration is KSTypeParameter)
                    domainDecl.asType(emptyList()).toTypeName()
                else typeName.toTypeName()

            val paramSpecBuilder = ParameterSpec.builder(name, type)

            // 3. (Optional but good practice) Handle modifiers like 'vararg'
            if (ksParameter.isVararg) {
                paramSpecBuilder.addModifiers(KModifier.VARARG)
            }

            // 4. (Optional) Handle default values
            // if (ksParameter.hasDefault) {
            //    paramSpecBuilder.defaultValue("...") // Note: Replicating default values is complex
            // }

            paramSpecBuilder.build()
        }
    }

    /**
     * Resolves a KSType from a generic superclass into a concrete TypeName.
     *
     * @param genericSuperClass The KSClassDeclaration of the generic interface (e.g., BaseRepository<T>)
     * @param concreteSubstition The KSClassDeclaration of the concrete type (e.g., MyDomain)
     * @param typeParamIndex The 0-based index of the type parameter to replace (default is 0 for T).
     */
    fun KSType.toResolvedTypeName(
        genericSuperClass: KSClassDeclaration,
        concreteSubstition: KSClassDeclaration,
        typeParamIndex: Int = 0
    ): TypeName {
        val typeDecl = this.declaration

        // Get the target type parameter from the superclass (e.g., 'T')
        val targetTypeParam = genericSuperClass.typeParameters.getOrNull(typeParamIndex)
            ?: return this.toTypeName() // Superclass has no type params, just return default

        return if (typeDecl is KSTypeParameter && typeDecl == targetTypeParam) {
            // This IS the type parameter (T), replace it with the concrete class
            concreteSubstition.toClassName()
        } else {
            // This is a concrete type (Unit, String) or a different type param
            this.toTypeName()
        }
    }

    companion object {
        /**
         * The default output file name used for generating repository implementations.
         * This constant is used in the code generation process to create output files
         * with a standardized and consistent naming convention.
         */
        private const val OUTPUT_FILENAME = "GeneratedEventRepositories"

        /**
         * Represents the option flag to enable context parameters for methods in repositories.
         * When this option is enabled, repository methods are expected to validate the presence
         * and correctness of a mandatory `context` parameter, which must be an instance of
         * `io.github.smyrgeorge.sqlx4k.QueryExecutor`.
         */
        private const val ENABLE_CONTEXT_PARAMETERS_OPTION: String = "enable-context-parameters"
    }
}
